package my.company.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TematicaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTematicaAllPropertiesEquals(Tematica expected, Tematica actual) {
        assertTematicaAutoGeneratedPropertiesEquals(expected, actual);
        assertTematicaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTematicaAllUpdatablePropertiesEquals(Tematica expected, Tematica actual) {
        assertTematicaUpdatableFieldsEquals(expected, actual);
        assertTematicaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTematicaAutoGeneratedPropertiesEquals(Tematica expected, Tematica actual) {
        assertThat(expected)
            .as("Verify Tematica auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTematicaUpdatableFieldsEquals(Tematica expected, Tematica actual) {
        assertThat(expected)
            .as("Verify Tematica relevant properties")
            .satisfies(e -> assertThat(e.getAbreviatura()).as("check abreviatura").isEqualTo(actual.getAbreviatura()))
            .satisfies(e -> assertThat(e.getDescripcion()).as("check descripcion").isEqualTo(actual.getDescripcion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTematicaUpdatableRelationshipsEquals(Tematica expected, Tematica actual) {}
}
